name: CI för Javascript-applikation
on: [push]

permissions:
  contents: read
  packages: write
jobs:
  unit-tests:
    uses: simonbrundin/deployment-pipeline/.github/workflows/run-tests-bun.yaml@main
    with:
      package-json-path: frontend
  build-publish-image:
    needs: unit-tests
    uses: simonbrundin/deployment-pipeline/.github/workflows/build-publish-image.yaml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      dockerfile: frontend/Dockerfile
      dockerfile-context: frontend
